-- Campos de acumulación de puntos en campañas de promociones.
IF COL_LENGTH('dbo.PROMOCIONES', 'FACTOR_PUNTOS') IS NULL
BEGIN
  ALTER TABLE dbo.PROMOCIONES ADD FACTOR_PUNTOS NUMERIC(18, 4) NULL;
END;
GO

IF COL_LENGTH('dbo.PROMOCIONES', 'TIPO') IS NULL
BEGIN
  ALTER TABLE dbo.PROMOCIONES ADD TIPO VARCHAR(50) NULL;
END;
GO

IF COL_LENGTH('dbo.PROMOCIONES', 'CODCLAUNO') IS NULL
BEGIN
  ALTER TABLE dbo.PROMOCIONES ADD CODCLAUNO INT NULL;
END;
GO
