-- Catálogo de departamentos de nómina por empresa
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'NOMINA_DEPARTAMENTOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.NOMINA_DEPARTAMENTOS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    CODIGO VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(120) NOT NULL,
    ACTIVO VARCHAR(2) NOT NULL CONSTRAINT DF_NOMINA_DEP_ACT DEFAULT ('SI'),
    CONSTRAINT UQ_NOMINA_DEPARTAMENTOS UNIQUE (EMPNIT, CODIGO),
    CONSTRAINT CK_NOMINA_DEP_ACTIVO CHECK (ACTIVO IN ('SI', 'NO'))
  );
  CREATE INDEX IX_NOMINA_DEPARTAMENTOS_EMP ON dbo.NOMINA_DEPARTAMENTOS (EMPNIT, ACTIVO);
END;
