-- Vales de caja chica (salida de efectivo desde cajas abiertas).
-- Esquema alineado a la tabla existente en SQL Server (PK identity NOVALE).
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'DOCUMENTOS_VALES_CAJA' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.DOCUMENTOS_VALES_CAJA (
    NOVALE INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(50) NULL,
    MES INT NULL,
    ANIO INT NULL,
    FECHA DATE NULL,
    CODCAJA INT NULL,
    TIPO VARCHAR(150) NULL,
    DESCRIPCION VARCHAR(250) NULL,
    RECIBE VARCHAR(150) NULL,
    IMPORTE FLOAT NULL,
    CORTE VARCHAR(2) NULL,
    NOCORTE FLOAT NULL
  );
  CREATE INDEX IX_DOCUMENTOS_VALES_CAJA_EMP_MES
    ON dbo.DOCUMENTOS_VALES_CAJA (EMPNIT, ANIO, MES);
  CREATE INDEX IX_DOCUMENTOS_VALES_CAJA_CAJA_CORTE
    ON dbo.DOCUMENTOS_VALES_CAJA (EMPNIT, CODCAJA, CORTE, FECHA);
END;
GO
