-- TASKS.CODEMPLEADO → empleado dueño de la tarea (Empleados.CODEMPLEADO)
IF COL_LENGTH('dbo.TASKS', 'CODEMPLEADO') IS NULL
BEGIN
  ALTER TABLE dbo.TASKS ADD CODEMPLEADO INT NULL;
END;
GO

IF NOT EXISTS (
  SELECT 1 FROM sys.indexes
  WHERE name = 'IX_TASKS_EMPNIT_CODEMPLEADO' AND object_id = OBJECT_ID('dbo.TASKS')
)
BEGIN
  CREATE INDEX IX_TASKS_EMPNIT_CODEMPLEADO ON dbo.TASKS (EMPNIT, CODEMPLEADO);
END;
GO
