-- Config: limita vales de caja al efectivo inicial de la caja abierta
IF NOT EXISTS (
  SELECT 1 FROM dbo.SETTINGS WHERE OPCION = N'LIMITA EFECTIVO DISPONIBLE EN VALES CAJA'
)
BEGIN
  INSERT INTO dbo.SETTINGS (OPCION, VALOR)
  VALUES (N'LIMITA EFECTIVO DISPONIBLE EN VALES CAJA', N'NO');
END;
GO
