-- Índices únicos para evitar duplicados (tras corregir datos existentes)
-- PRODUCTOS: EMPNIT + CODPROD
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WHERE name = N'UQ_PRODUCTOS_EMPNIT_CODPROD' AND object_id = OBJECT_ID(N'dbo.PRODUCTOS')
)
BEGIN
  CREATE UNIQUE NONCLUSTERED INDEX [UQ_PRODUCTOS_EMPNIT_CODPROD]
    ON dbo.PRODUCTOS (EMPNIT, CODPROD);
END
GO

-- INVSALDO: EMPNIT + CODPROD
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WHERE name = N'UQ_INVSALDO_EMPNIT_CODPROD' AND object_id = OBJECT_ID(N'dbo.INVSALDO')
)
BEGIN
  CREATE UNIQUE NONCLUSTERED INDEX [UQ_INVSALDO_EMPNIT_CODPROD]
    ON dbo.INVSALDO (EMPNIT, CODPROD);
END
GO

-- PRECIOS: EMPNIT + CODPROD + CODMEDIDA
IF NOT EXISTS (
  SELECT 1 FROM sys.indexes WHERE name = N'UQ_PRECIOS_EMPNIT_CODPROD_CODMEDIDA' AND object_id = OBJECT_ID(N'dbo.PRECIOS')
)
BEGIN
  CREATE UNIQUE NONCLUSTERED INDEX [UQ_PRECIOS_EMPNIT_CODPROD_CODMEDIDA]
    ON dbo.PRECIOS (EMPNIT, CODPROD, CODMEDIDA);
END
GO
