-- Suscripciones de servicios (TIPOPROD = S) por cliente y empresa
IF EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'SUSCRIPCIONES' AND schema_id = SCHEMA_ID('dbo')
) AND NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'DOCUMENTOS_SUSCRIPCIONES' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  EXEC sp_rename 'dbo.SUSCRIPCIONES', 'DOCUMENTOS_SUSCRIPCIONES';
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'DOCUMENTOS_SUSCRIPCIONES' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  CREATE TABLE dbo.DOCUMENTOS_SUSCRIPCIONES (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    CODCLIENTE INT NOT NULL,
    CODPROD VARCHAR(30) NOT NULL,
    COBRO_MENSUAL DECIMAL(18, 3) NOT NULL CONSTRAINT DF_DOCUMENTOS_SUSCRIPCIONES_COBRO DEFAULT (0),
    PAGADO_MES VARCHAR(2) NOT NULL CONSTRAINT DF_DOCUMENTOS_SUSCRIPCIONES_PAGADO DEFAULT ('NO'),
    MESES_DEBE INT NOT NULL CONSTRAINT DF_DOCUMENTOS_SUSCRIPCIONES_MESES DEFAULT (0),
    ACTIVO VARCHAR(2) NOT NULL CONSTRAINT DF_DOCUMENTOS_SUSCRIPCIONES_ACTIVO DEFAULT ('SI'),
    OBS VARCHAR(255) NULL,
    FECHA_INICIO DATE NULL,
    CONSTRAINT UQ_DOCUMENTOS_SUSCRIPCIONES UNIQUE (EMPNIT, CODCLIENTE, CODPROD)
  );

  CREATE INDEX IX_DOCUMENTOS_SUSCRIPCIONES_EMPNIT ON dbo.DOCUMENTOS_SUSCRIPCIONES (EMPNIT);
END;
