-- Campos extras nómina: Departamento, BonoLey, BonoAdicional
-- NOMINA_EMPLEADO (datos fijos del empleado) + NOMINA_DETALLE (planilla)

IF COL_LENGTH('dbo.NOMINA_EMPLEADO', 'DEPARTAMENTO') IS NULL
  ALTER TABLE dbo.NOMINA_EMPLEADO ADD DEPARTAMENTO VARCHAR(120) NULL;

IF COL_LENGTH('dbo.NOMINA_EMPLEADO', 'BONO_LEY') IS NULL
  ALTER TABLE dbo.NOMINA_EMPLEADO ADD BONO_LEY DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_EMP_BONO_LEY DEFAULT (0);

IF COL_LENGTH('dbo.NOMINA_EMPLEADO', 'BONO_ADICIONAL') IS NULL
  ALTER TABLE dbo.NOMINA_EMPLEADO ADD BONO_ADICIONAL DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_EMP_BONO_ADI DEFAULT (0);

IF COL_LENGTH('dbo.NOMINA_DETALLE', 'DEPARTAMENTO') IS NULL
  ALTER TABLE dbo.NOMINA_DETALLE ADD DEPARTAMENTO VARCHAR(120) NULL;

IF COL_LENGTH('dbo.NOMINA_DETALLE', 'BONO_LEY') IS NULL
  ALTER TABLE dbo.NOMINA_DETALLE ADD BONO_LEY DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_BONO_LEY DEFAULT (0);

IF COL_LENGTH('dbo.NOMINA_DETALLE', 'BONO_ADICIONAL') IS NULL
  ALTER TABLE dbo.NOMINA_DETALLE ADD BONO_ADICIONAL DECIMAL(18, 3) NOT NULL CONSTRAINT DF_NOMINA_DET_BONO_ADI DEFAULT (0);
