-- Opción de configuración: SOLICITA AUTORIZACIONES (SI/NO)
IF NOT EXISTS (
  SELECT 1 FROM dbo.SETTINGS WHERE OPCION = N'SOLICITA AUTORIZACIONES'
)
BEGIN
  INSERT INTO dbo.SETTINGS (OPCION, VALOR) VALUES (N'SOLICITA AUTORIZACIONES', N'NO');
END
GO
