-- Archivo de documentos eliminados (snapshot JSON para auditoría/soporte).
-- Ejecutar vía Actualizador BD (UPDATE_QUERIES) o directamente en SQL Server.
-- También se crea en runtime con ensureTable al eliminar o consultar.

IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'DOCUMENTOS_ELIMINADOS' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  CREATE TABLE dbo.DOCUMENTOS_ELIMINADOS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    CODDOC VARCHAR(50) NOT NULL,
    CORRELATIVO DECIMAL(18, 0) NOT NULL,
    TIPODOC VARCHAR(10) NULL,
    FECHA_DOC DATE NULL,
    FECHA_ELIMINACION DATETIME NOT NULL CONSTRAINT DF_DOCUMENTOS_ELIMINADOS_FECHA DEFAULT (GETDATE()),
    USUARIO VARCHAR(50) NULL,
    MOTIVO NVARCHAR(255) NULL,
    PAYLOAD NVARCHAR(MAX) NOT NULL
  );

  CREATE INDEX IX_DOCUMENTOS_ELIMINADOS_EMP_FECHA
    ON dbo.DOCUMENTOS_ELIMINADOS (EMPNIT, FECHA_ELIMINACION DESC);

  CREATE INDEX IX_DOCUMENTOS_ELIMINADOS_EMP_DOC
    ON dbo.DOCUMENTOS_ELIMINADOS (EMPNIT, CODDOC, CORRELATIVO);
END;
