-- Opción: CERTIFICA AL FINALIZAR (SI | NO)
IF NOT EXISTS (SELECT 1 FROM dbo.SETTINGS WHERE OPCION = 'CERTIFICA AL FINALIZAR')
BEGIN
  INSERT INTO dbo.SETTINGS (OPCION, VALOR) VALUES ('CERTIFICA AL FINALIZAR', 'NO');
END
GO

-- Opción: MUESTRA FORMATO FEL ONLINE (NO | SI | AMBOS)
IF NOT EXISTS (SELECT 1 FROM dbo.SETTINGS WHERE OPCION = 'MUESTRA FORMATO FEL ONLINE')
BEGIN
  INSERT INTO dbo.SETTINGS (OPCION, VALOR) VALUES ('MUESTRA FORMATO FEL ONLINE', 'NO');
END
GO
