-- Control de fletes por empresa / periodo
IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'CONTROL_FLETES' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  CREATE TABLE dbo.CONTROL_FLETES (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    MES INT NOT NULL,
    ANIO INT NOT NULL,
    NOPEDIDO VARCHAR(50) NULL,
    FECHA_ING DATE NULL,
    FECHA_VEN DATE NULL,
    UGC DECIMAL(18, 4) NULL,
    TROPICAL DECIMAL(18, 4) NULL,
    COL_5800 DECIMAL(18, 4) NULL,
    HORCALZA DECIMAL(18, 4) NULL,
    M_BCO DECIMAL(18, 4) NULL,
    M_XTRA DECIMAL(18, 4) NULL,
    M_GRIS DECIMAL(18, 4) NULL,
    LEVAN DECIMAL(18, 4) NULL,
    MAX_P DECIMAL(18, 4) NULL,
    PLTA VARCHAR(50) NULL,
    PLACA VARCHAR(30) NULL,
    TR_FLET DECIMAL(18, 4) NULL,
    COSTO DECIMAL(18, 4) NULL,
    ABASTO VARCHAR(200) NULL,
    FLETE DECIMAL(18, 4) NULL,
    SALDO DECIMAL(18, 4) NULL,
    STATUS VARCHAR(15) NOT NULL CONSTRAINT DF_CONTROL_FLETES_STATUS DEFAULT ('PENDIENTE')
  );

  CREATE INDEX IX_CONTROL_FLETES_EMP_PERIODO
    ON dbo.CONTROL_FLETES (EMPNIT, ANIO, MES);

  CREATE INDEX IX_CONTROL_FLETES_EMP_STATUS
    ON dbo.CONTROL_FLETES (EMPNIT, STATUS);
END;
