-- Control de asistencia por empleado (entrada / salida del día)
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CONTROL_ASISTENCIA' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.CONTROL_ASISTENCIA (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    FECHA DATE NOT NULL,
    CODEMPLEADO INT NOT NULL,
    HORA_ENTRADA TIME(0) NULL,
    HORA_SALIDA TIME(0) NULL,
    USUARIO VARCHAR(80) NULL,
    CONSTRAINT UQ_CONTROL_ASISTENCIA UNIQUE (EMPNIT, FECHA, CODEMPLEADO)
  );
  CREATE INDEX IX_CONTROL_ASISTENCIA_EMP_FECHA
    ON dbo.CONTROL_ASISTENCIA (EMPNIT, FECHA);
  CREATE INDEX IX_CONTROL_ASISTENCIA_EMPLEADO
    ON dbo.CONTROL_ASISTENCIA (EMPNIT, CODEMPLEADO, FECHA);
END;
