-- Tareas pendientes por empresa
IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'TASKS' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  CREATE TABLE dbo.TASKS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    TAREA VARCHAR(500) NULL,
    RESPONSABLE VARCHAR(100) NULL,
    PRIORIDAD VARCHAR(10) NOT NULL CONSTRAINT DF_TASKS_PRIORIDAD DEFAULT ('BAJA'),
    ST VARCHAR(15) NOT NULL CONSTRAINT DF_TASKS_ST DEFAULT ('PENDIENTE'),
    HORA INT NULL,
    MINUTO INT NULL,
    FECHA DATE NULL,
    SYNC VARCHAR(2) NULL
  );

  CREATE INDEX IX_TASKS_EMPNIT ON dbo.TASKS (EMPNIT);
END;
