-- Entregas parciales de facturas (Pendientes Entrega)
IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'DOCUMENTOS_ENTREGAS' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  CREATE TABLE dbo.DOCUMENTOS_ENTREGAS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(50) NOT NULL,
    CODDOC VARCHAR(30) NOT NULL,
    CORRELATIVO DECIMAL(18, 0) NOT NULL,
    FECHA DATE NOT NULL,
    HORA INT NULL,
    MINUTO INT NULL,
    ENTREGADO_A VARCHAR(255) NOT NULL,
    USUARIO VARCHAR(100) NULL,
    DETALLE NVARCHAR(MAX) NOT NULL,
    TOTALUNIDADES DECIMAL(18, 4) NULL,
    FECHA_REG DATETIME NOT NULL CONSTRAINT DF_DOCUMENTOS_ENTREGAS_FECHA_REG DEFAULT (GETDATE())
  );

  CREATE INDEX IX_DOCUMENTOS_ENTREGAS_DOC
    ON dbo.DOCUMENTOS_ENTREGAS (EMPNIT, CODDOC, CORRELATIVO, ID DESC);
END;
