-- Plantillas de impresión por empresa y tipo de documento (TIPODOC)
IF NOT EXISTS (
  SELECT 1 FROM sys.tables WHERE name = 'FORMATOS_IMPRESION' AND schema_id = SCHEMA_ID('dbo')
)
BEGIN
  CREATE TABLE dbo.FORMATOS_IMPRESION (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(20) NOT NULL,
    TIPODOC VARCHAR(10) NOT NULL,
    PAPEL VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    HTML NVARCHAR(MAX) NOT NULL,
    CSS NVARCHAR(MAX) NULL,
    ACTIVO VARCHAR(2) NOT NULL CONSTRAINT DF_FORMATOS_IMPRESION_ACTIVO DEFAULT ('SI'),
    FECHA_MOD DATETIME NULL,
    USUARIO_MOD VARCHAR(50) NULL,
    CONSTRAINT UQ_FORMATOS_IMPRESION UNIQUE (EMPNIT, TIPODOC, PAPEL)
  );

  CREATE INDEX IX_FORMATOS_IMPRESION_EMPNIT ON dbo.FORMATOS_IMPRESION (EMPNIT);
  CREATE INDEX IX_FORMATOS_IMPRESION_TIPODOC ON dbo.FORMATOS_IMPRESION (EMPNIT, TIPODOC);
END;
GO
