-- Columnas FISICO en INVSALDO / PRODUCTOS + backfill opcional de ENTREGADOS
-- para tipodocs que no usan entrega parcial (no FAC/FEF/FEC/FES/FEL).
-- Uso: Actualizador BD o node scripts/seed-update-query-invsaldo-fisico.js

-- @UPDATER_CHUNK INVSALDO_FISICO_COL
IF COL_LENGTH('dbo.INVSALDO', 'FISICO') IS NULL
BEGIN
  ALTER TABLE dbo.INVSALDO ADD FISICO FLOAT NULL;
END;

-- @UPDATER_CHUNK PRODUCTOS_FISICO_COL
IF COL_LENGTH('dbo.PRODUCTOS', 'FISICO') IS NULL
BEGIN
  ALTER TABLE dbo.PRODUCTOS ADD FISICO FLOAT NULL;
END;

-- @UPDATER_CHUNK DOCPRODUCTOS_ENTREGADOS_BACKFILL
-- Tipodocs sin entrega parcial: ENTREGADOS_* debe igualar TOTAL* (físico al operar).
IF COL_LENGTH('dbo.DOCPRODUCTOS', 'ENTREGADOS_TOTALUNIDADES') IS NOT NULL
BEGIN
  UPDATE lp
  SET
    lp.ENTREGADOS_TOTALUNIDADES = ISNULL(lp.TOTALUNIDADES, 0),
    lp.ENTREGADOS_TOTALPRECIO = ISNULL(lp.TOTALPRECIO, 0),
    lp.ENTREGADOS_TOTALCOSTO = ISNULL(lp.TOTALCOSTO, 0)
  FROM dbo.DOCPRODUCTOS lp
  INNER JOIN dbo.DOCUMENTOS d
    ON d.EMPNIT = lp.EMPNIT
   AND d.CODDOC = lp.CODDOC
   AND d.CORRELATIVO = lp.CORRELATIVO
  INNER JOIN dbo.TIPODOCUMENTOS t
    ON t.EMPNIT = d.EMPNIT
   AND t.CODDOC = d.CODDOC
  WHERE UPPER(LTRIM(RTRIM(ISNULL(t.TIPODOC, '')))) NOT IN ('FAC', 'FEF', 'FEC', 'FES', 'FEL')
    AND ISNULL(lp.TIPOM, 0) <> 0
    AND ISNULL(lp.TIPOPROD, 'P') <> 'S'
    AND (
      ISNULL(lp.ENTREGADOS_TOTALUNIDADES, 0) = 0
      AND ISNULL(lp.TOTALUNIDADES, 0) <> 0
    );
END;
