-- Pagos / canjes de puntos de promociones (carné = CODIGO de PROMOCIONES_REGISTROS).
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'PROMOCIONES_PAGOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
  CREATE TABLE dbo.PROMOCIONES_PAGOS (
    ID INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    EMPNIT VARCHAR(50) NOT NULL,
    IDPROMO INT NOT NULL,
    CODIGO INT NOT NULL,
    FECHA DATE NOT NULL,
    PUNTOS NUMERIC(18, 4) NOT NULL CONSTRAINT DF_PROMOCIONES_PAGOS_PUNTOS DEFAULT (0),
    IMPORTE NUMERIC(18, 4) NOT NULL CONSTRAINT DF_PROMOCIONES_PAGOS_IMPORTE DEFAULT (0),
    CONSTRAINT FK_PROMOCIONES_PAGOS_PROMO
      FOREIGN KEY (IDPROMO) REFERENCES dbo.PROMOCIONES (ID) ON DELETE CASCADE
  );
  CREATE INDEX IX_PROMOCIONES_PAGOS_EMP_CODIGO ON dbo.PROMOCIONES_PAGOS (EMPNIT, CODIGO);
  CREATE INDEX IX_PROMOCIONES_PAGOS_PROMO ON dbo.PROMOCIONES_PAGOS (IDPROMO, FECHA);
END;
GO
