-- Opción de configuración: GUARDADO DE FOTOS (LOCAL | HOST)
IF NOT EXISTS (SELECT 1 FROM dbo.SETTINGS WHERE OPCION = 'GUARDADO DE FOTOS')
BEGIN
  INSERT INTO dbo.SETTINGS (OPCION, VALOR) VALUES ('GUARDADO DE FOTOS', 'LOCAL');
END
GO
