-- Opción: DEFAULT TIPO DOCUMENTO FINALIZADO (FEF | FAC | FEC)
IF NOT EXISTS (SELECT 1 FROM dbo.SETTINGS WHERE OPCION = N'DEFAULT TIPO DOCUMENTO FINALIZADO')
BEGIN
  INSERT INTO dbo.SETTINGS (OPCION, VALOR) VALUES (N'DEFAULT TIPO DOCUMENTO FINALIZADO', N'FEF');
END
GO
